# Generated by Django 2.2.5 on 2019-09-23 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 9, 23, 12, 0)),
            preserve_default=False,
        ),
    ]
